#! /bin/bash
# This script generates a system report in a nice format in a log file and also prints it on the terminal screen

# Calculate the free space on the hard drive and extract meaningful info
freespace=$(df -h / | grep -E "\/$" | awk '{print $4}')
# Set colors and styles for using later
greentext="\033[32m"
bold="\033[1m"
normal="\033[0m"
logdate=$(date +"%Y%m%d") # Store date in a variable
logfile="$logdate"_report.log # Use date to make a variable for a log file name

echo -e $bold"Quick system report for "$greentext"$HOSTNAME"$normal
printf "\tSystem type:\t%s\n" $MACHTYPE
printf "\tBash Version:\t%s\n" $BASH_VERSION
printf "\tFree Space:\t%s\n" $freespace
printf "\tFiles in dir:\t%s\n" $(ls | wc -l)
printf "\tGenerated on:\t%s\n" $(date +"%d/%m/%y") 
echo -e $greentext"A summary of this info has been saved to $logfile"$normal

cat <<- EOF > $logfile
	This report was automatically generated by my Bash script.
	It contains a brief summary of some system information.
EOF

printf "SYS:\t%s\n" $MACHTYPE >> $logfile
printf "BASH:\t%s\n" $BASH_VERSION >> $logfile
printf "SPACE:\t%s\n" $freespace >> $logfile